# Generated by Django 4.2.16 on 2024-11-26 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('cur_unit', models.CharField(max_length=10)),
                ('ttb', models.CharField(max_length=10)),
                ('tts', models.CharField(max_length=10)),
                ('deal_bas_r', models.CharField(max_length=10)),
                ('bkpr', models.CharField(max_length=10)),
                ('yy_efee_r', models.CharField(max_length=10)),
                ('ten_dd_efee_r', models.CharField(max_length=10)),
                ('kftc_bkpr', models.CharField(max_length=10)),
                ('kftc_deal_bas_r', models.CharField(max_length=10)),
                ('cur_nm', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('dcls_month', models.CharField(max_length=50)),
                ('fin_co_no', models.CharField(max_length=20)),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('kor_co_nm', models.CharField(max_length=50)),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.CharField(max_length=50)),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.CharField(max_length=2)),
                ('join_member', models.TextField()),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField()),
                ('dcls_strt_day', models.CharField(max_length=50)),
                ('dcls_end_day', models.CharField(max_length=50, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=20)),
                ('fin_co_no', models.CharField(max_length=20)),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('intr_rate_type', models.CharField(max_length=50)),
                ('intr_rate_type_nm', models.CharField(max_length=50)),
                ('rsrv_type', models.CharField(max_length=50, null=True)),
                ('rsrv_type_nm', models.CharField(max_length=50, null=True)),
                ('save_trm', models.CharField(max_length=20)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_deposit', models.FloatField()),
                ('avg_withdraw', models.FloatField()),
                ('avg_save', models.FloatField()),
                ('sum_deposit', models.IntegerField()),
                ('sum_withdraw', models.IntegerField()),
                ('sumSave', models.IntegerField()),
                ('savings_rate', models.IntegerField()),
                ('expense_rate', models.IntegerField()),
                ('content', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=products.models.default_end_date)),
                ('member_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
